from django.db import transaction
from courses.models import Course, Module, CachedLesson
import json
import uuid # For unique IDs

# Import the corrected fallback utility
from core.utils.ai_fallback import call_ai_with_fallback 

def trigger_module_generation(course: Course):
    """
    Generates 15 Modules and their corresponding CachedLessons for a given Course 
    using the AI Fallback system.
    """
    # ... (Omitted Syllabus lookup, assuming it will be added by the team)
    
    # --- AI Prompt Construction ---
    prompt = f"""
    You are an expert Nigerian education curriculum planner. Generate a structured 
    study plan consisting of EXACTLY 15 modules for a student preparing for the 
    {course.exam_type} exam in the subject: {course.subject}.
    
    The output MUST be a single JSON list of 15 objects. Each object must have 
    two keys: "title" (a concise module title) and "topic" (a single specific 
    syllabus topic covered by the module).
    
    JSON Output Format Example:
    [
        {{"title": "Introduction to Linear Motion", "topic": "Uniform acceleration and deceleration"}},
        ... (13 more modules)
    ]
    """
    
    # 1. Call the AI using the new arguments
    # Set max_tokens high enough for 15 module titles/topics. is_json MUST be True.
    result = call_ai_with_fallback(prompt, max_tokens=1500, is_json=True) 
    
    if not result['success']:
        # Circuit Breaker was triggered or all tiers failed
        print(f"AI Module Generation Failed for Course {course.id}. Tier: {result.get('tier')}")
        return False
    
    response_text = result['content']
    
    # 2. Parse the JSON response (FIXED LOGIC)
    try:
        # Find the start of the JSON list ('[') and the end (']')
        json_start = response_text.find('[')
        json_end = response_text.rfind(']') # Find the last ']'
        
        if json_start == -1 or json_end == -1:
             raise ValueError("Could not find valid JSON list boundaries.")

        # Extract only the content between the first [ and the last ]
        # json_end + 1 ensures the final ']' is included
        clean_json_text = response_text[json_start:json_end + 1]
        
        module_list = json.loads(clean_json_text)
        
        # Basic sanity check
        if not isinstance(module_list, list) or len(module_list) == 0:
             raise ValueError("AI response was not a valid JSON list object.")
             
    except (json.JSONDecodeError, ValueError) as e:
        # Note the specific error during parsing
        print(f"JSON Parsing Failed for Course {course.id}: Error: {e}")
        return False
    
    # --- Data Saving ---
    
    # 3. Save Modules and Placeholder Lessons
    with transaction.atomic():
        for index, item in enumerate(module_list):
            
            # A. Create a Placeholder CachedLesson
            # A background task would replace the content later.
            lesson_to_use = CachedLesson.objects.create(
                topic=item.get('topic', 'Unspecified Topic'),
                content="Placeholder: Content is being generated by AI (Async Task).",
                syllabus_version="V1.0", 
                # requested_by=course.user 
                cache_key=str(uuid.uuid4()), # Generate a unique ID
            )

            # B. Create the Module linking to the Course and the Lesson
            Module.objects.create(
                course=course,
                title=item.get('title', 'Untitled Module'),
                order=index + 1,
                syllabus_topic=item.get('topic', 'Unspecified Topic'),
                lesson_content=lesson_to_use
            )
            
        # 4. Deduct Credits (If applicable, ensure this is done)
        # course.user.deduct_credits(amount=5)
        
    return True