# Generated by Django 5.2.8 on 2025-11-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_cachedlesson_requested_by_module_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedlesson',
            name='cache_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
